ALTER TABLE sel.schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE sel.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE sel.lineup ENABLE ROW LEVEL SECURITY;
ALTER TABLE sel.heats ENABLE ROW LEVEL SECURITY;
ALTER TABLE sel.telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE sel.stats ENABLE ROW LEVEL SECURITY;