name: db

on:
    workflow_run:
        workflows: ["sel data"]
        types:
            - completed
    workflow_dispatch:
env:
  DATA_BRANCH: sel

jobs:
    data:
        runs-on: ubuntu-latest
        steps:
            - name: checkout data branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ env.DATA_BRANCH }}
