name: Test action

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start season'
        required: true
        default: '2023'
        type: string
      end:
        description: 'Last season'
        required: true
        default: '2023'
        type: string
env:
  URL: https://ekstraliga.pl/en/se/fixtures-and-results/pgee


jobs:
  schedules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout data-store-test
        uses: actions/checkout@v4
        with:
          ref: data-store-test
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-test
          path: actions-test
      - name: Fetch schedule
        run: |
          for i in {${{ github.event.inputs.start }}..${{ github.event.inputs.end }}}; do
            mkdir -p data/sel/$i
            curl -f --no-progress-meter $URL/$i -o data/sel/$i/schedule.html
          done
      - name: list files
        run: ls -lah data/sel/2023/schedule.html
      - name: Commit and push changes
        id: commit
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" && echo "changes=1" >> $GITHUB_OUTPUT
          git push
