name: Test action

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start season'
        required: true
        default: 2023
        type: number
      end:
        description: 'Last season'
        required: true
        default: 2023
        type: number

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to environment
      run: |
        for i in {${{ github.event.inputs.start }}..${{ github.event.inputs.end }}}; do
          mkdir -p data/sel/$i
          echo "SEASON $i" > schedule
        done
