name: Test action

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start season'
        required: true
        default: '2023'
        type: string
      end:
        description: 'Last season'
        required: true
        default: '2023'
        type: string
      schedule_cache:
        description: 'Use cached schedule'
        required: true
        default: false
        type: boolean
      match_cache:
        description: 'Use cached match'
        required: true
        default: false
        type: boolean
      force:
        description: 'Force recompute'
        required: true
        default: false
        type: boolean
env:
  SCHEDULE_URL: https://ekstraliga.pl/en/se/fixtures-and-results/pgee
  MATCH_URL: https://ekstraliga.pl/en/se/match


jobs:
  schedules:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.commit.outputs.changes }}
    permissions:
      contents: write
    steps:
      - name: checkout data-store-test
        uses: actions/checkout@v4
        with:
          ref: data-store-test
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-test
          path: actions-test
      - name: Fetch schedule
        if: ${{ github.event.inputs.schedule_cache == 'false' }}
        run: |
          for i in $(seq $START $END); do
            mkdir -p data/sel/$i
            curl -f --no-progress-meter $SCHEDULE_URL/$i -o data/sel/$i/schedule.html
          done
        env:
          START: ${{ github.event.inputs.start }}
          END: ${{ github.event.inputs.end }}
      - name: process files
        run: |
          for i in $(seq $START $END); do
            node actions-test/src/index.js schedule data/sel/$i/schedule.html > data/sel/$i/schedule.json
          done
        env:
          START: ${{ github.event.inputs.start }}
          END: ${{ github.event.inputs.end }}
      - name: Commit and push changes
        id: commit
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" && echo "changes=1" > $GITHUB_OUTPUT
          # commit_status=$?
          if [ "$FORCE" = "true" ]; then
              echo "changes=1" > $GITHUB_OUTPUT
          fi
          git push
        env:
          FORCE: ${{ github.event.inputs.force }}
  match:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: schedules
    if: needs.schedules.outputs.changes == '1'
    steps:
      - name: checkout data-store-test
        uses: actions/checkout@v4
        with:
          ref: data-store-test
          fetch-depth: 0
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-test
          path: actions-test
      - name: schedule changes force
        if: ${{ github.event.inputs.force == 'true' }}
        run: |
          for season in $(seq $START $END); do
            jq -c 'select(.status.id == 1)' data/sel/$season/schedule.json | tee -a CHANGES;
          done
        env:
          START: ${{ github.event.inputs.start }}
          END: ${{ github.event.inputs.end }}
      - name: schedule changes
        if: ${{ github.event.inputs.force == 'false' }}
        run: |
          echo "CHANGED FILES"
          for file in $(git diff --name-only --diff-filter=M HEAD^ HEAD); do
              # check if the file exists and is a json file
              if [[ -e "$file" && "$file" == *schedule.json ]]; then
                  echo $file;
                  # get the hashes of the commits that modified the file excet the most recent one
                  hash=$(git log -n 2 --pretty=format:%h -- $file | tail -n 1);
                  diff -e <(git show "$hash:$file" | jq -c 'select(.status.id == 1)') \
                  <(jq -c 'select(.status.id == 1)' $file) \
                  | sed '1d;$d' | tee -a CHANGES;
              fi
          done

          echo "ADDED FILES"
          for file in $(git diff --name-only --diff-filter=A HEAD^ HEAD); do
              if [[ -e "$file" && "$file" == *schedule.json ]]; then
                  echo $file;
                  jq -c 'select(.status.id == 1)' $file | tee -a CHANGES;
              fi;
          done
      - name: get match data
        if: ${{ github.event.inputs.match_cache == 'false' }}
        run: |
          while IFS= read -r line; do
            id=$(echo "$line" | jq -r '.id')
            season=$(echo "$line" | jq -r '.season')
            mkdir -p "data/sel/$season/match/html"
            echo "$MATCH_URL/$id"
            curl -f --no-progress-meter "$MATCH_URL/$id" -o "data/sel/$season/match/html/$id.html"
            # Generate a random number between  1 and  500 (to represent milliseconds)
            random_milliseconds=$(( RANDOM %  400 +  100  ))
            # Convert milliseconds to seconds and sleep
            sleep_seconds=$(echo "scale=2; $random_milliseconds /  1000" | bc)
            sleep $sleep_seconds
          done < CHANGES
      - name: process match files
        run: |
          if [ -f CHANGES ]; then
            while IFS= read -r line; do
              id=$(echo "$line" | jq -r '.id')
              season=$(echo "$line" | jq -r '.season')
              mkdir -p "data/sel/$season/match/json"
              node actions-test/src/index.js match "data/sel/$season/match/html/$id.html" > "data/sel/$season/match/json/$id.json"
            done < CHANGES
          fi
      - name: Commit and push changes
        id: commit
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || true
          git push