name: Test action

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start season'
        required: true
        default: '2023'
        type: string
      end:
        description: 'Last season'
        required: true
        default: '2023'
        type: string
      schedule_cache:
        description: 'Use cached schedule'
        required: true
        default: false
        type: boolean
      match_cache:
        description: 'Use cached match'
        required: true
        default: false
        type: boolean
      force:
        description: 'Force recompute'
        required: true
        default: false
        type: boolean
env:
  SCHEDULE_URL: https://ekstraliga.pl/en/se/fixtures-and-results/pgee
  MATCH_URL: https://ekstraliga.pl/en/se/match


jobs:
  schedules:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.commit.outputs.changes }}
    permissions:
      contents: write
    steps:
      - name: checkout data-store-test
        uses: actions/checkout@v4
        with:
          ref: data-store-test
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-test
          path: actions-test
      - name: Fetch schedule
        if: ${{ github.event.inputs.schedule_cache == 'false' }}
        run: |
          for i in $(seq $START $END); do
            mkdir -p data/sel/$i
            curl -f --no-progress-meter $SCHEDULE_URL/$i -o data/sel/$i/schedule.html
          done
        env:
          START: ${{ github.event.inputs.start }}
          END: ${{ github.event.inputs.end }}
      - name: process files
        run: |
          for i in $(seq $START $END); do
            node actions-test/src/index.js data/sel/$i/schedule.html > data/sel/$i/schedule.json
          done
        env:
          START: ${{ github.event.inputs.start }}
          END: ${{ github.event.inputs.end }}
      - name: Commit and push changes
        id: commit
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" && echo "changes=1" > $GITHUB_OUTPUT
          # commit_status=$?
          if [ "$FORCE" = "true" ]; then
              echo "changes=1" > $GITHUB_OUTPUT
          fi
          git push
        env:
          FORCE: ${{ github.event.inputs.force }}
  match:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: schedules
    if: needs.schedules.outputs.changes == '1'
    steps:
      - name: checkout data-store-test
        uses: actions/checkout@v4
        with:
          ref: data-store-test
          fetch-depth: 0
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-test
          path: actions-test
      - name: Check file content
        run: cat data/sel/2023/schedule.json
      - name: Check jq installation
        run: jq --version
      - name: Print working directory
        run: |
          pwd
          ls -laqh data/sel/2023/
      - name: debug
        run: |
          if [ "$FORCE" = "true" ]; then
            echo "Forcing recompute"
            for season in $(seq $START $END); do
              jq -c 'select(.id == 5276)' data/sel/$season/schedule.json | tee -a CHANGES;
            done
          fi
        env:
          START: ${{ github.event.inputs.start }}
          END: ${{ github.event.inputs.end }}
          FORCE: ${{ github.event.inputs.force }}
      # - name: diff changes
      #   run: |
      #     if [ "$FORCE" = "true" ]; then
      #       for i in {${{ github.event.inputs.start }}..${{ github.event.inputs.end }}}; do
      #         jq -c 'select(.status.id == 5276)' data/sel/$i/schedule.json | tee -a CHANGES;
      #       done
      #     fi
      #   env:
      #     FORCE: ${{ github.event.inputs.force }}
      - name: get match data
        if: ${{ github.event.inputs.match_cache == 'false' }}
        run: |
          while IFS= read -r line; do
            id=$(echo "$line" | jq -r '.id')
            season=$(echo "$line" | jq -r '.season')
            mkdir -p "data/sel/$season/match/html"
            echo "$MATCH_URL/$id"
            curl -f --no-progress-meter "$MATCH_URL/$id" -o "data/sel/$season/match/html/$id.html"
            # Generate a random number between  1 and  500 (to represent milliseconds)
            random_milliseconds=$(( RANDOM %  400 +  100  ))
            # Convert milliseconds to seconds and sleep
            sleep_seconds=$(echo "scale=2; $random_milliseconds /  1000" | bc)
            sleep $sleep_seconds
          done < CHANGES
      - name: process match files
        run: |
          # for every season in the range list the files in the directory and process them
          for season in $(seq $START $END); do
            mkdir -p "data/sel/$season/match/json"
            for file in data/sel/$season/match/html/*.html; do
              echo $file
              # node actions-test/src/match.js $file > data/sel/$season/match/json/$(basename $file .html).json
            done
          done
        env:
          START: ${{ github.event.inputs.start }}
          END: ${{ github.event.inputs.end }}
      - name: Commit and push changes
        id: commit
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}"
          git push