name: sel db

on:
    workflow_run:
        workflows: ["sel data"]
        types:
            - completed
    workflow_dispatch:
env:
  DATA_BRANCH: sel

jobs:
    data:
        environment: spdw-sel
        runs-on: ubuntu-latest
        permissions:
          contents: read
          actions: read
        steps:
            - name: checkout data branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ env.DATA_BRANCH }}
            - name: install duckdb
              run: |
                curl -L --retry 3 --retry-delay 5 -o duckdb_cli-linux-amd64.zip https://github.com/duckdb/duckdb/releases/download/v1.3.2/duckdb_cli-linux-amd64.zip
                unzip duckdb_cli-linux-amd64.zip
                chmod +x duckdb
                sudo mv duckdb /usr/local/bin/
            - name: Verify DuckDB install
              run: duckdb --version
            - name: db export
              run: |
                mkdir -p parquet
                duckdb sel.db -c "EXPORT DATABASE 'parquet' (FORMAT parquet);"
                ls -lah parquet
            - name: db upload
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
                AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
                BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
                AWS_REQUEST_CHECKSUM_CALCULATION: ${{ vars.AWS_REQUEST_CHECKSUM_CALCULATION }}
              run: |
                aws --version
                aws s3 cp --recursive parquet/ s3://$BUCKET
                aws s3 cp sel.db s3://$BUCKET
