name: Workflow2

on:
  workflow_dispatch:
    inputs:
        force:
            description: 'Force run'
            required: true
            default: false
            type: boolean

jobs:
    test1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run tests
              run: echo "Running tests"            